## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    print "Someone called build on PILO"
    obj = bld.create_ns3_program('pilo-base', ['csma', 'internet', 'applications'])
    obj.source = 'pilo.cc'
